name: deploy

on: workflow_dispatch
  # push:
  #   branches:
  #     - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: build
        run: |
          pnpm i
          pnpm run build

      - name: rsync deployment
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: --recursive --delete --chmod=ugo-rX -vvvv
          path: ./dist/
          remote_path: /var/www/sourcetorio-site/
          legacy_allow_rsa_hostkeys: "true"
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_KEY }}